FROM node:16-alpine

RUN npx create-react-app t23

WORKDIR /t23

CMD ["npm", "start"]

# dockfile basico que cria um CONTAINER com uma aplicação REACT
# docker run -it t23:v1
# docker run -itd --name container3 --network trybe-networkig busybox
# docker network connect CONTAINER REDE 